//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busTimesTagTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("busTimesTagTests.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;SEM:1986&quot;,&quot;name&quot;:&quot;GRENOBLE, CASERNE DE BONNE&quot;,&quot;lon&quot;:5.72533,&quot;lat&quot;:45.18506,&quot;lines&quot;:[&quot;SEM:13&quot;,&quot;SEM:16&quot;,&quot;SEM:C4&quot;,&quot;SEM:13&quot;,&quot;SEM:16&quot;,&quot;SEM:C4&quot;]},{&quot;id&quot;:&quot;SEM:1987&quot;,&quot;name&quot;:&quot;GRENOBLE, CASERNE DE BONNE&quot;,&quot;lon&quot;:5.72542,&quot;lat&quot;:45.18509,&quot;lines&quot;:[&quot;SEM:16&quot;,&quot;SEM:16&quot;]},{&quot;id&quot;:&quot;SEM:0754&quot;,&quot;name&quot;:&quot;GRENOBLE, DOCTEUR MARTIN&quot;,&quot;lon&quot;:5.72728,&quot;lat&quot;:45.18731,&quot;lines&quot;:[&quot;SEM:C1&quot;,&quot;SEM:57&quot;,&quot;SEM:C4&quot;,&quot;SEM:C1&quot;,&quot;SEM:57&quot;,&quot;SEM:C4&quot;]},{&quot;id&quot;:&quot;SEM:4331&quot;,&quot;name&quot;:&quot;GRENOBLE, DOCTEUR MARTIN&quot;,&quot;lon&quot;:5.72832,&quot;lat&quot;:45.18738,&quot;lines&quot;:[&quot;SEM:13&quot;,&quot;SEM:16&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Json {
            get {
                return ResourceManager.GetString("Json", resourceCulture);
            }
        }
    }
}
